### PR TITLE
Support Electron 9, 10 and 11

### PR DESCRIPTION
**Pull request by ykhwong**
## Description
Build iohook for electron 9 and 10

## Motivation and Context
For details, please refer to #241

### CODE REVIEW

**Comment by Djiit** [comment]
Hey @ykhwong, Thanks for all this work, this is awesome.
Could you please provide a "build" script ? i.e. the build script is still using cmale-js and I don't know how to replace it.

Thanks

**Comment by Djiit** [comment]
Allright, I've pushed a commit (remove cmake-js, add fs-extra dependency). Now, I have this error: 
`make: *** No rule to make target `Release/obj.target/uiohook/build_def/darwin/libuiohook/src/logger.o', needed by `Release/uiohook.dylib'.  Stop.`

Any idea ?

**Comment by ykhwong** [comment]
> Allright, I've removed cmake-js, added fs-extra dev dependency on my local machine. Can't push on your branch. Now, I have this error:
> `make: *** No rule to make target `Release/obj.target/uiohook/build_def/darwin/libuiohook/src/logger.o', needed by `Release/uiohook.dylib'. Stop.`
> 
> Any idea ?

The error occurred because Node-gyp could not handle symbolic .gyp links properly on Linux and macOS. I fixed the issue by copying the gyp files manually.

Encountered another weird error on travis-ci though: `gyp ERR! stack Error: ENOENT: no such file or directory, mkdir '/home/travis/.cache/node-gyp/4.0.4'`

**Comment by Djiit** [comment]
Great! Your last commit passed on Travis 👍

**Comment by ykhwong** [comment]
> Could you please provide a "build" script ? i.e. the build script is still using cmale-js and I don't know how to replace it.

I have no idea how the build script should work. I've just redirected the build command to execute the build.js without upload. Please tell me if I am doing wrong. Thanks.

**Comment by Djiit** [comment]
I think it's great. I've been able to compile and run the example on my
machine. Congrats ! Will finish the review later today.

--
Julien

**Comment by Djiit** [comment]
The compilation goes well but then I'm unable to use the compiled files. Here is what I have : 
```
> iohook-electron-example@1.0.0 start /Users/jtanay/Projects/Djiit/iohook/examples/electron-example
> electron ./

App threw an error during load
Error: dlopen(/Users/jtanay/Projects/Djiit/iohook/builds/electron-v82-darwin-x64/build/Release/iohook.node, 1): Library not loaded: @rpath/uiohook.dylib
  Referenced from: /Users/jtanay/Projects/Djiit/iohook/builds/electron-v82-darwin-x64/build/Release/iohook.node
```

Are you able to run the example in `examples/electron-example`, or could you tell me how to use the compiled files ?

**Comment by ykhwong** [comment]
Please understand that I have no mac for testing, which makes me hard to debug. Try again and let me know the result.

**Comment by Djiit** [comment]
No changes with your recent commits :( .

Can you describe me what you run to use iohook ?

e.g. : 
```
node build.js (...)
(copy stuff in your project?)
npm start 
```

So I can try to do the same on macos.

Thanks

**Comment by ykhwong** [comment]
I assumed that rpath does not get resolved properly, so instructed the node-gyp to get the correct path of the iohook module. Could you try again with the last commit, please?

Here are commands that I executed for testing with node-v10 on Ubuntu x64.
```npm i --no-scripts
npm run build -- --runtime=node --version=10.0.0 --abi=64
mkdir -p builds/node-v64-linux-x64/build/Release/
cp build/Release/* builds/node-v64-linux-x64/build/Release/.
rm -rf build/Release
npm run test```

**Comment by LayneTheEpic** [comment]
Any update on this? I've been digging around the web for any solution to electron + iohook (build documentation is poor) without going back too far in electron versions

**Comment by Djiit** [comment]
Hey, I didn't have time to re-test everything. Last time I did, I was not able to have the same result. If anyone wants to help, we need to validate the author's change before merging and releasing a new version.

**Comment by marcelblum** [comment]
Hello, I took a stab at some testing tonight building on Mac 10.13 and Windows 10 and had (mostly) success with Electron 9:

Untitled

Screen Shot 2020-12-02 at 12 32 17 AM

(also made a new Electron example demo app for testing which I found helpful, it uses iohook directly in the renderer process which has several advantages, in case you want to try it I submitted a pr https://github.com/marcelblum/iohook/pull/1)

Some issues I observed:

- when `npm install`ing on both Win & Mac there were lots of errors related to robotjs. Didn't seem to impede building though.

- After starting iohook from the Electron example there is a ton of logging noise in the node console, see pics above. Not sure if this is intentional, maybe invoking iohook via ./index.js activates some verbose debugging mode? Excuse my ignorance if this is expected.

- On Windows some keyboard keys are not triggering iohook events, though they do produce logging output in the node console: Testing with a full USA QWERTY keyboard, all "navigation keys" (insert, home, arrows, etc.) and function keys are ignored, and also if numlock is off all numpad keys are ignored as well. These keys were all trapped successfully in the previous release 0.6.6.

- On Mac also some keys are not being trapped: Testing with a small laptop keyboard (13" Macbook Pro w/Touchbar), the down arrow and all touchbar-forced function keys are ignored. As above, these key events are still all logged in the node console, and these keys were all working fine in the previous release 0.6.6. Did not yet get a chance to test on Mac with a full keyboard.

- On Windows the node console often showed the following message, not sure if this is expected but I never saw it with the previous release: "Restarting Windows input hook on window event: 0X800C."

**Comment by marcelblum** [comment]
Update: Tested on Mac today with a full size generic USB keyboard. The following keys not firing keydown events (but as noted above are producing logging output in the Node console): all F-keys, down arrow, insert, home, end, pgup, pgdown. So not exactly the same keys not working in Windows with this build.

**Comment by majidbigdeli** [comment]
> Hello, I took a stab at some testing tonight building on macOS 10.13 and Windows 10 and had (mostly) success with Electron 9:
> 
> Untitled
> 
> Screen Shot 2020-12-02 at 12 32 17 AM
> 
> (also made a new Electron example demo app for testing which I found helpful, it uses iohook directly in the renderer process which has several advantages, in case you want to try it I submitted a pr #265)
> 
> Some issues I observed:
> 
> * when `npm install`ing on both Win & Mac there were lots of errors related to robotjs. Didn't seem to impede building though.
> * After starting iohook from the Electron example there is a ton of logging noise in the node console, see pics above. Not sure if this is intentional, maybe invoking iohook via ./index.js activates some verbose debugging mode? Excuse my ignorance if this is expected but I never saw this with the previous release 0.6.6.
> * On Windows some keyboard keys are not triggering iohook keydown events, though they do produce logging output in the node console: Testing with a full USA QWERTY keyboard, all "navigation keys" (insert, home, arrows, etc.) and function keys are ignored, and also if numlock is off all numpad keys are ignored as well. These keys were all trapped successfully in the previous release 0.6.6.
> * On Mac also some keys are not being trapped: Testing with a small laptop keyboard (13" Macbook Pro w/Touchbar), the down arrow and all touchbar-forced function keys are ignored. As above, these key events are still all logged in the node console, and these keys were all working fine in the previous release 0.6.6. Did not yet get a chance to test on Mac with a full keyboard.
> * On Windows the node console often showed the following message, not sure if this is expected but I never saw it with the previous release: "Restarting Windows input hook on window event: 0X800C."

@marcelblum , @Djiit  Yes .  I test in  Windows 10 and Electron 11.0.3
I get same Result

**Comment by LayneTheEpic** [comment]
Oh it works for 11 as well? That's sweet!
Any time reference for when this will be merged?

**Comment by marcelblum** [comment]
Just realized why those random keys weren't firing events - it was because the stale examples folder demos I was testing with use the deprecated `keypress` iohook event listener. And I had copied that code into my "new" electron example and... GIGO! I've now replaced them both with `keydown` (https://github.com/wilix-team/iohook/pull/266) and all is working 100% now, no more missed key events!! Awesome!

**Comment by marcelblum** [comment]
And yeah I also tried compiling with an electron 11 (abi 85) target and it totally works:

Untitled

Awesome work by @ykhwong !

**Comment by marcelblum** [comment]
And I'm an idiot, the only reason for the verbose logging I was complaining about is because the examples use `ioHook.start(true)` to force debug mode, duh...

**Comment by ericwooley** [comment]
This is exciting!

I really need this for electron 10, if I can help in any way let me know. sign me up for the alpha test, or whatever is needed. I am not familiar enough with the project to help much with the code. But I believe in you guys! :clap:

**Comment by majidbigdeli** [comment]
> This is exciting!
> 
> I really need this for electron 10, if I can help in any way let me know. sign me up for the alpha test, or whatever is needed. I am not familiar enough with the project to help much with the code. But I believe in you guys! 👏

ok . you can clone  this project  and build for your abi eg in electron 11.0.3 is abi is 85

**Comment by Djiit** [comment]
I was able to reproduce everything (node 14, electron 9 and 11) locally. Thanks @ykhwong for this awesome work. I'll merge this and work on a release.

**Comment by Djiit** [comment]
So, build is working, but the prebuilt are now. If anyone wants to help. I'm creating an issue.

**Pull request merged**
