### PR TITLE
Fix app freezing (fixes: #93)

### PR DESCRIPTION
**Pull request by Luke265**
When running multiple apps with iohook, mouse/key inputs becomes very laggy, sometimes even completely frozen.

## Description

I am not a c++ programmer, and I am not exactly sure what I did here.

## Motivation and Context

See #93 
## How Has This Been Tested?

With the patch iohook installs locally on Windows 10.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Djiit** [comment]
I'm closing this for now. Feel free to reopen it if you want to.

**Comment by sentialx** [comment]
@Djiit Why it has been closed?

**Comment by Wizek** [comment]
Hey @Luke265, do you understand why this PR was closed? Was there some issue with it that might not be apparent for me and sentialx? Or was its closure confusing for you too?

**Comment by Luke265** [comment]
@Wizek Sorry, I don't know why this PR was closed. I had no issues, so far, using iohook with this PR.

**Comment by Djiit** [comment]
Hi guys, Sorry if I closed this too soon. I thought it was not necessary and it didn't have any activity.

**Comment by Wizek** [comment]
Thanks @Djiit for reopening!

So, in the interest of moving forward with this issue getting fixed, I tried out this patch. However, the mouse-freezing is still present when I ran this test:

```
const {exec} = require('child_process');
const iohook = require('iohook');

iohook.start();

if (process.argv.length === 2) {
	console.log('Launched main');
	iohook.on('keydown', (e) => {
		console.log('Main', e.rawcode);
	});
	exec([`"${process.argv[0]}"`, process.argv[1], '-t'].join(' ')).stdout.pipe(process.stdout);
} else {
	console.log('Launched child');
	iohook.on('keydown', (e) => {
		console.log('Child', e.rawcode);
	});
}
```

Even when I set 

```
{
  "devDependencies": {
    "iohook": "github:Luke265/iohook#patch-1"
  }
}
```

You can find my repro-repo over here: https://github.com/Wizek/iohook-test. Just 

```
git clone https://github.com/Wizek/iohook-test
cd iohook-test
npm i
node .
```

Could you @Luke265 do the above test and tell me if your mouse lags after that code runs on Windows, preferably Windows 10?

Also, @Djiit, could you also do this just so you can see how bad this bug is?

**Comment by Wizek** [comment]
Did you manage to try the repro steps @Luke265 and @Djiit? It's really as simple as:

```
git clone https://github.com/Wizek/iohook-test
cd iohook-test
npm i
node .
```

At least I could get some confirmation that others are also experiencing the same issue on Windows 10 as I.

**Comment by Wizek** [comment]
As this is still not fixed, I'm switching over to something that seems to work better: 

https://www.npmjs.com/package/gkm

**Comment by zxc23** [comment]
I also get the freezing when running multiple iohook apps at the same time. I haven't been able to try the PR but I support the effort.

**Comment by WilixLead** [comment]
Hello guys. @Luke265 @Wizek if any one have time to check this PR https://github.com/wilix-team/iohook/pull/294 - will be cool. Looks like it exactly the same issue for windows systems

**Comment by WilixLead** [comment]
Closing it regarding https://github.com/wilix-team/iohook/pull/294

**Pull request closed without merging**
