### PR TITLE
WIP: Resolves a character on 'Keypress'

### PR DESCRIPTION
**Pull request by matthewshirley**
## Description
- When the 'keypress' event is called it will convert the 'keychar' to a character.
- Keycode on a 'keypress' is will use the int of keychar
- Removed 'use strict'
- Removed 'npm run build' from appveyor because the deploy command already does this.
 
## Motivation and Context
Saves users having to resolve this in the JS

## Screenshots (if appropriate):
keychar

## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] New feature (a non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by Djiit** [comment]
Does it work on a non-QWERTY keyboard ? I use a fr_FR keyboard and had difficulties to match Linux keycode to actual chars.

**Comment by matthewshirley** [comment]
@Djiit I don't think it does.

I tested on fr_CA, Windows and it didn't correctly match accents. Let's hold off on this for now.

**Comment by Djiit** [comment]
Ok, that's what we found earlier. As a user suggest, would it make sense to ship this AND warn the user it only maps to a standard, en_US QWERTY keyboard layout ?

**Comment by matthewshirley** [comment]
Sounds like a plan. Does String.fromCharCode() with the keycode resolve the correct character for you?

**Comment by Djiit** [comment]
Finally had some times to test it out -- and nope, it doesn't resolve the correct character; most of the time no character (or at least no printable character) at all.

**Comment by DCzajkowski** [comment]
#74 may help 😉

**Comment by jadengore** [comment]
@matthewshirley Tested out your branch, and I'm getting this error:
```
ist [628]: Could not find keyboard map for locale 0000000004090409!
refresh_locale_list [470]: GetKeyboardLayoutList(0, NULL) found 1 layouts.
refresh_locale_list [487]: Received 1 locales.
load_input_helper [860]: refresh_locale_list() found 0 locale(s).
```

I also logged the event, which looks like this:
```json
{ keycode: 30, rawcode: 65, type: "keydown", mask: 0 }
```

Any ideas on how we can load the locale for the keychar properly?

**Comment by WilixLead** [comment]
@matthewshirley Hi. What is state of this PR ?

**Comment by matthewshirley** [comment]
This PR is dead ☠️

**Pull request closed without merging**
