### PR TITLE
Bump cmake-js version and add electron v4

### LINKED ISSUE #144: Electron 4 support?
Any chance we can get electron 4 (electron-v69) support?

### PR DESCRIPTION
**Pull request by anoadragon453**
Fixes #144 

Bumping the cmake-js version as suggested in the above issue allows Electron v4 to compile :+1:

### CODE REVIEW

**Comment by anoadragon453** [comment]
So the CI does not pass. But it builds on my computer. However I'm only trying to build Electron v3.0.0, v4.0.4, so perhaps older Electrons are failing.

**Comment by anoadragon453** [comment]
Yep, so I can definitely confirm that building with this and inserting into an Electron v4 app, everything works. Will try and figure out the CI issues tomorrow :+1:

**Comment by anoadragon453** [comment]
Whelp it's tomorrow (sorta?). This got stuck behind other things but I'm back on the case now. Currently trying to make sure everything builds on all platforms. Wish me luck.

**Comment by anoadragon453** [comment]
So for people having trouble with the build saying it requires a C++11 compiler, add the following line to your CMakeLists.txt file:

```
set (CMAKE_CXX_STANDARD 11)
```

right after `use_c99()`.

This file will probably need some updating. Can confirmed this helped build successfully on MacOS.

**Comment by anoadragon453** [comment]
So the Windows build seems to be failing due to `cmake` having it's generator `-G` set to `Visual Studio 14 2015 Win64 Win64`. There's an extra `Win64` in there. Anyone know where this is coming from?

**Comment by anoadragon453** [comment]
Well that seems to have worked.

**Comment by Djiit** [comment]
Wow 🎉

**Comment by Djiit** [comment]
Frankly he CI was setup a long time ago by another volunteer. So the next steps would be : 
- bump to at least 0.4.0 (you can do it !)
- merge (i'll do it)
- release to npm when the CI is ok on master (i'll do it)

Aaaaand we're done :)

**Comment by Djiit** [comment]
About Electron 4.0.0, it is indeed 67 before 4.0.4. I think we can omit it here.

**Comment by anoadragon453** [comment]
Bumped.

**Pull request merged**
