### PR TITLE
Moved @types/node to devDependencies and updated version in package-lock

### PR DESCRIPTION
**Pull request by metaa**
Installing `@types/node` as a normal dependency really doesn't make much sense.

### CODE REVIEW

**Comment by Djiit** [comment]
Hi there ! Thanks for your contribution !

Appveyor fails because it doesn't install dev dependencies. You can try to add `-D`to this line https://github.com/wilix-team/iohook/blob/master/appveyor.yml#L23

**Comment by Djiit** [comment]
Hmmm, actually that didn't do the trick... It complais about a non-existing var. See https://github.com/nodejs/node/issues/25132 .
Would you like to investigate it further ? You may want to find which dependency use `native` and bump it so we have a correct native version. I'll have a look when I can.

**Comment by metaa** [comment]
I'm pretty busy right now, but I might have a look later if no one else did by then.

**Comment by metaa** [comment]
I noticed that AppVeyor seems to build on Windows while Travis uses Linux.
The issue you linked mentioned [this package](https://www.npmjs.com/package/natives) which - on the other hand - mentions
> the (undocumented!) `--expose-internals` flag

I will add that to the test, at least to see what's happening here on Windows.

**Comment by metaa** [comment]
AppVeyor is weird ...
After nearly 20 minutes [it failed with `UnhandledPromiseRejectionWarning: Error: Error from GitHub: Bad credentials`](https://ci.appveyor.com/project/Djiit/iohook/builds/22943734/job/5ewrby2unka2do5k#L3564) 🤔

Hey another thought, shouldn't this script actually also use [npm ci](https://docs.npmjs.com/cli/ci.html) instead of `npm i`?

**Comment by metaa** [comment]
help?

**Comment by metaa** [comment]
🎉

**Comment by Djiit** [comment]
Finally had some time to close all of this :). Thanks !!

**Pull request merged**
