### PR TITLE
fix: Disable startup logs

### LINKED ISSUE #219: Don't show debug information when imported
## Expected Behavior
`iohook` should be imported without creating any noise in the terminal.

## Current Behavior
It is logging this:
```
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 2 layouts.
refresh_locale_list [493]: Received 2 locales.
load_input_helper [866]: refresh_locale_list() found 2 locale(s).
```

## Possible Solution
Silently perform this in the background and only alert if failed.

## Steps to Reproduce (for bugs)
```js
require("iohook")
```

## Context
I want to be able to silently import `iohook` without it spitting information in the terminal.

## Your Environment

* Version used: 0.6.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js 13.7.0
* Operating System and version (desktop or mobile): Windows 10

cc @Djiit

### PR DESCRIPTION
**Pull request by Richienb**
Fixes #219 

cc @Djiit

### CODE REVIEW

**Comment by Richienb** [comment]
cc @Djiit Please review.

**Comment by Djiit** [comment]
Hey,

Are we sure we want to completely disable these logs ? I never saw them, it might be related to the log level you set on your side ?

**Comment by Richienb** [comment]
@Djiit As far as I can tell, the function that is supposed to be handling the messages (https://github.com/wilix-team/iohook/blob/master/src/iohook.cc#L42-L65) isn't assigned properly so the debug checks don't work. Therefore, the only way I see is to disable the verbose stdout logs or somehow rewrite parts of libuiohook to be working again.

**Comment by Djiit** [comment]
I get it,but is it possible to modify only iohook files and not libiohook ?

Sorry I can't really help on this.

**Comment by WilixLead** [comment]
Closing this due no activity

**Pull request closed without merging**
