### PR TITLE
Support Electron v13-14 and Node v16

### PR DESCRIPTION
**Pull request by ykhwong**
Support Electron v13-14 and Node v16

### CODE REVIEW

**Comment by quuu** [comment]
bump please ^

**Comment by ykhwong** [comment]
If we don't use AppVeyor anymore, please consider deleting AppVeyor's webhook from the repo setting.

**Comment by ash0x0** [comment]
@ykhwong did you test using this? platform, env?

**Comment by ykhwong** [comment]
Yes, I tested with electron abi-89 and win10 x86_64 and confirmed it to work. I don't have a testing environment for the other platforms for now.

**Comment by sonukapoor** [comment]
@ykhwong Would you mind providing a fix for 15 as well? I am sure a lot of people will appreciate that.

**Comment by ykhwong** [comment]
> @ykhwong Would you mind providing a fix for 15 as well? I am sure a lot of people will appreciate that.

You can find it here: https://github.com/wilix-team/iohook/pull/363

**Comment by sonukapoor** [comment]
Thanks @ykhwong. Does this also fix the non-context-aware error mentioned here?

https://github.com/wilix-team/iohook/pull/387

**Comment by ykhwong** [comment]
> Thanks @ykhwong. Does this also fix the non-context-aware error mentioned here?
> 
> #387

I don't think so.

**Comment by sonukapoor** [comment]
@ykhwong Any idea how to fix this?

**Comment by ykhwong** [comment]
@sonukapoor I haven't encountered the 'non-context-aware' error with the pull request branch ykhwong:update-electron-v15, so I have no idea how to fix it.

**Comment by sonukapoor** [comment]
@ykhwong If you try to load the module in the renderer you should see an error. The solution is to use `NAN_MODULE_WORKER_ENABLED` as mentioned in the linked PR. @marcelblum mentioned though that the clean up is missing, so the PR is sitting there for an C++ expert to come and help.

**Comment by marcelblum** [comment]
@sonukapoor sad to say but unfortunately you're better off just using the actively maintained [uiohook-napi](https://github.com/SnosMe/uiohook-napi) which works well in latest Electron. iohook seems to be dead.

**Comment by sonukapoor** [comment]
@marcelblum Do you know how to use this within the Electron renderer?

**Comment by marcelblum** [comment]
@sonukapoor uiohook-napi works just like iohook, almost a drop-in replacement. I found a few keycodes were different in certain platform-specific situations but that was pretty much the only difference. uiohook-napi binds to the same uiohook library.

**Comment by sonukapoor** [comment]
@marcelblum I was trying to load this using `__non_webpack_require` and the prebuilt version for windows, but it doesnt seem to work. I get the `node.napi.node is not a valid Win32 application`. I will try to import it directly.

**Pull request merged**
